name: "Code Scanning - Action"

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

  workflow_dispatch:

jobs:
  Audit:
    runs-on: windows-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp

      - name: Build
        run: |
          Import-Module .\.github\Invoke-VisualStudio.ps1
          Invoke-VisualStudio2022x64
          cmake -S . -B ./build -A x64
          cmake --build ./build --verbose --config Debug

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
