name: "Build Driver"

env:
  PROJECT: changeme
  AUTHOR: hugsy
  VERBOSE: 1
  CMAKE_FLAGS: "-DDEBUG=ON"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: "Building ${{ matrix.os }}/${{ matrix.platform }}/${{ matrix.configuration }}"

    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        platform: ['x64', 'x86', 'arm64']
        configuration: ['RelWithDebInfo']

    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Sets Environment Variables
      shell: powershell
      run: |
        echo "NB_CPU=$env:NUMBER_OF_PROCESSORS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Prepare Windows environment
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        Import-Module .\.github\Invoke-VisualStudio.ps1
        Invoke-VisualStudio2022${{ matrix.platform }}

    - name: Build source
      run: |
        cmake -S . -B build ${{ env.CMAKE_FLAGS }}
        cmake --build ./build --verbose --parallel ${{ env.NB_CPU }} --config ${{ matrix.configuration }}

    - name: Prepare artifact
      run: |
        mkdir artifact
        cmake --install ./build --config ${{ matrix.configuration }} --prefix ./artifact --verbose

    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT }}_${{ github.ref_name }}_${{ matrix.os }}_${{ matrix.platform }}_${{ github.sha }}
        path: artifact/
        avatar_url: ${{ github.actor.avatar_url }}
