name: "Build Driver"

env:
  PROJECT: changeme
  AUTHOR: hugsy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    env:
      VERBOSE: 1
      NB_CPU: 1
      CMAKE_FLAGS:

    name: "win${{ matrix.windows_version }}/${{ matrix.platform }}/${{ matrix.configuration }}"

    strategy:
      fail-fast: false
      matrix:
        windows_version: ['2022', '2019']
        platform: ['x64', 'win32', 'arm64']
        configuration: ['RelWithDebInfo', 'Debug']

    runs-on: windows-${{ matrix.windows_version }}
    permissions:
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Sets Environment Variables
      shell: powershell
      run: |
        echo "NB_CPU=$env:NUMBER_OF_PROCESSORS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Prepare Windows environment
      shell: pwsh
      run: |
        Import-Module .\.github\Invoke-VisualStudio.ps1
        Invoke-VisualStudio${{ matrix.windows_version }}${{ matrix.platform }}

    - name: Build source
      run: |
        cmake -S . -B build -A ${{ matrix.platform }} ${{ env.CMAKE_FLAGS }}
        cmake --build ./build --verbose --parallel ${{ env.NB_CPU }} --config ${{ matrix.configuration }}

    - name: Prepare artifact
      run: |
        mkdir artifact
        cmake --install ./build --config ${{ matrix.configuration }} --prefix ./artifact --verbose

    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT }}_${{ github.ref_name }}_win${{ matrix.windows_version }}_${{ matrix.platform }}_${{ matrix.configuration }}_${{ github.sha }}
        path: artifact/
